// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCugu9ZF8ZlfwtbDCIQAhPMtQ25Hj0XTCU',
    appId: '1:535603853746:web:b7a5c1709b18481e228cab',
    messagingSenderId: '535603853746',
    projectId: 'flutterecommerce-2ceaa',
    authDomain: 'flutterecommerce-2ceaa.firebaseapp.com',
    storageBucket: 'flutterecommerce-2ceaa.firebasestorage.app',
    measurementId: 'G-LHPC2019YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEyODwPC8fBsU7GwXkFj2ze5BmaPqvXmU',
    appId: '1:535603853746:android:fcdb9440c99c4c80228cab',
    messagingSenderId: '535603853746',
    projectId: 'flutterecommerce-2ceaa',
    storageBucket: 'flutterecommerce-2ceaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiDV_URo4ckIY4TS3rawqm-I90lO-H8lQ',
    appId: '1:535603853746:ios:033e031c411ae553228cab',
    messagingSenderId: '535603853746',
    projectId: 'flutterecommerce-2ceaa',
    storageBucket: 'flutterecommerce-2ceaa.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiDV_URo4ckIY4TS3rawqm-I90lO-H8lQ',
    appId: '1:535603853746:ios:033e031c411ae553228cab',
    messagingSenderId: '535603853746',
    projectId: 'flutterecommerce-2ceaa',
    storageBucket: 'flutterecommerce-2ceaa.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCugu9ZF8ZlfwtbDCIQAhPMtQ25Hj0XTCU',
    appId: '1:535603853746:web:5d5faf5683330017228cab',
    messagingSenderId: '535603853746',
    projectId: 'flutterecommerce-2ceaa',
    authDomain: 'flutterecommerce-2ceaa.firebaseapp.com',
    storageBucket: 'flutterecommerce-2ceaa.firebasestorage.app',
    measurementId: 'G-QQFGRLFLDF',
  );
}
